### PR TITLE
Update readme

### LINKED ISSUE #50: Update README
Update README to reflect different uses cases of the gem, and code examples.

### PR DESCRIPTION
**Pull request by inveterateliterate**
Largely reorganized the ReadMe to bring up the installation and usage, and leave the "philosophy" to the end.

Appreciate any other thoughts on organization, or whether the `Motivation` section should be less philosophy and more just on value add, or something like that. 

I did update some of the writing itself, so please do read through.

Resolves #50

### CODE REVIEW

**Review by dpikt — COMMENTED** [review]
This is great! My one suggestion would be to switch the order of the `Details` and `Advanced` sections.

**Review by rkillackey — COMMENTED** [review]
Looks good! Agreed with David about switching the sections. I also think it's still a bit long...might consider removing the Motivation section? It seems like that content was communicated across other sections

**Comment by inveterateliterate** [comment]
I'm good with removing the motivation stuff. We can always use that in promotional communications.

**Comment by dpikt** [comment]
@inveterateliterate changes look good to me! I'd say merge away unless @francirp has any extra input.

**Comment by francirp** [comment]
LGTM! Merge away.

**Review by dpikt — APPROVED** [review]
👍

**Pull request merged**
